{% set data = load_setup_py_data() %}
package:
    name: xml2table
    version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
    path: ..

build:
    number: 1
    script: python3 setup.py install

requirements:
    build:
        - python >=3.8
        - setuptools <60.0
    run:
        - python >=3.8
        - numpy >=1.8*

about:
    home: https://github.com/Xemin0/XML2Table
    license: BSD 3-Clause
    license_file: LICENSE
    license_family: BSD

    summary: data['description']
