name: build_and_publish_conda

on:
    release:
    types: [published]


jobs:
    publish:
        runs-on: MacOS-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: publish-to-conda
          uses: MichaelsJP/conda-package-publish-action@v1.0.0
          with:
            subDir: './conda-recipe'
            AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
            platforms: 'all'
            override: true
            dry_run: false
