name: build_and_publish_conda

on:
    release:
      types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v1

        - name: set Anaconda Upload
          run: conda config --set anaconda_upload yes

        - name: publish-to-conda
          uses: jegp/conda-package-publish-action@v1.6
          with:
            subDir: './conda-recipe'
            AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
