name: build_and_publish_conda

on:
    release:
      types: 
        - published


jobs:
    publish:
        runs-on: Ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v1

        - name: set Anaconda Upload
          run: conda config --set annaconda_upload yes

        - name: publish-to-conda
          uses: MichaelsJP/conda-package-publish-action@v1.1.0
          with:
            subDir: './conda-recipe'
            AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
            platforms: 'all'
            override: true
            dry_run: false
