name: build_and_publish_conda

on:
    release:
      types: ['released', 'prereleased']

# workflow_dispatch

jobs:
    conda_deployment_with_new_tag:
        name: Conda deployment of package with Python ${{ matrix.python--version }}
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [macOS-latest, ubuntu-latest, windows-latest]
            python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        steps:
        - name: Checkout Code
          uses: actions/checkout@v3
          with: 
            fetch-depth: 0
        - name: Conda environment creation and activation
          uses: conda-incubator/setup-miniconda@v2
          with:
            python-version: ${{ matrix.python-version }}
            environment-file: ./conda-envs/build_env.yaml
            auto-update-conda: false
            auto-activate-base: false
            show-channel-urls: true
        - name: Build and upload the conda packages
          uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
          with:
            meta_yaml_dir: ./conda-recipe
            python-version: ${{ matrix.python-version }}
            #platform_linux-64: true
            #platform_osx-64: true
            #platform_win-64: true
            #platform_osx-arm64: true
            user: xemin0
            label: auto
            overwrite: true
            token: ${{ secrets.ANACONDA_TOKEN }}

